dat <- read.csv2("household_power_consumption.txt", stringsAsFactors = FALSE)
dat$Date_time <- strptime(paste(dat$Date,dat$Time),"%d/%m/%Y %H:%M:%S")
dat$Global_active_power <- (as.numeric(dat$Global_active_power))
sub <- dat[dat$Date == "1/2/2007" | dat$Date == "2/2/2007",]
png(file = "plot4.png", width = 480, height = 480, bg = "transparent")
par(mfrow = c(2, 2))
plot(sub$Date_time, sub$Global_active_power, pch = NA, xlab = NA, ylab = "Global Active Power")
lines(sub$Date_time, sub$Global_active_power)
plot(sub$Date_time, sub$Voltage, pch = NA, xlab = "datetime", ylab = "Voltage")
lines(sub$Date_time, sub$Voltage)
plot(sub$Date_time, sub$Sub_metering_1, pch = NA, xlab = NA, ylab = "Energy sub metering")
lines(sub$Date_time, sub$Sub_metering_1, col = "black")
lines(sub$Date_time, sub$Sub_metering_2, col = "red")
lines(sub$Date_time, sub$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
plot(sub$Date_time, sub$Global_reactive_power, pch = NA, xlab = "datetime", ylab = "Global_reactive_power")
lines(sub$Date_time, sub$Global_reactive_power)
dev.off()